Logistics/Controllers/ChangepwdController.cs
using Logistics.Filters;
using Logistics.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Logistics.Controllers
{
    public class ChangepwdController : Controller
    {
        //
        // GET: /Changpwd/
        [ActionAuthentication]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ActionAuthentication]
        public JsonResult ChangePassword(UserModel user)
        {
            if (Session[CookieModel.UserName.ToString()] == null || string.IsNullOrEmpty(Session[CookieModel.UserName.ToString()].ToString()))
            {
                Redirect("Login/Index");
                return null;
            }
            JsonResult json = new JsonResult() { ContentType = "text/html" };
            int result = 0;
            user.UserName = Session[CookieModel.UserName.ToString()].ToString();
            string message = ValidateInput(user);
            if (!string.IsNullOrEmpty(message))
            {
                json.Data = new { Result = 0, Message = message };
                return json;
            }
            try
            {
                user.Password = Md5Encrypt.CreateInstance().Encrypt(user.Password);
                user.Password_New = Md5Encrypt.CreateInstance().Encrypt(user.Password_New);
                result = ServiceModel.CreateInstance().Client.ModifyPassword(user.UserName, user.Password, user.Password_New);
                switch (result)
                { 
                    case -1:
                        message = "没有权限";
                        break;
                    case 0:
                        message = "旧密码输入不正确";
                        break;
                    case 1:
                        message = "修改成功";
                        break;
                }
            }
            catch (Exception ex)
            {
                result = 0;
                message = ex.Message;
            }
            json.Data = new { Result = result, Message = message };
            return json;
        }

        private string ValidateInput(UserModel user)
        {
            string message = string.Empty;
            if (string.IsNullOrEmpty(user.Password))
            {
                message = "旧密码不能为空";
                return message;
            }
            if (user.Password.Length < 6 || user.Password.Length > 20)
            {
                message = "旧密码为6-20位字符";
                return message;
            }
            if (string.IsNullOrEmpty(user.Password_New))
            {
                message = "新密码不能为空";
                return message;
            }
            if (user.Password_New.Length < 6 || user.Password_New.Length > 20)
            {
                message = "新密码为6-20位字符";
                return message;
            }
            if (string.IsNullOrEmpty(user.Password_Confirm))
            {
                message = "确认密码不能为空";
                return message;
            }
            if (user.Password_Confirm.Length < 6 || user.Password_Confirm.Length > 20)
            {
                message = "确认密码为6-20位字符";
                return message;
            }
            if ( user.Password_New!= user.Password_Confirm)
            {
                message = "新密码和确认密码输入不一致";
                return message;
            }
            return message;
        }
    }
}

Logistics/Controllers/QueryController.cs
using Logistics.Filters;
using Logistics.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Logistics.Controllers
{
    public class QueryController : Controller
    {
        //
        // GET: /Query/
        [ActionAuthentication]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ActionAuthentication]
        public JsonResult GetProject(ProjectModel project)
        {
            if (Session[CookieModel.UserName.ToString()] == null || string.IsNullOrEmpty(Session[CookieModel.UserName.ToString()].ToString()))
            {
                Redirect("Login/Index");
                return null;
            }
            JsonResult json = new JsonResult() { ContentType = "text/html" };
            try
            {
                project.ProjectStatus = string.IsNullOrEmpty(project.ProjectStatus) ? string.Empty : project.ProjectStatus;
                project.CustomerName = string.IsNullOrEmpty(project.CustomerName) ? string.Empty : project.CustomerName;
                project.CustomerTel = string.IsNullOrEmpty(project.CustomerTel) ? string.Empty : project.CustomerTel;
                project.ProjectAddress = string.IsNullOrEmpty(project.ProjectAddress) ? string.Empty : project.ProjectAddress;
                project.ProjectType = string.IsNullOrEmpty(project.ProjectType) ? string.Empty : project.ProjectType;
                project.MachineType = string.IsNullOrEmpty(project.MachineType) ? string.Empty : project.MachineType;
                project.StartDate = string.IsNullOrEmpty(project.StartDate) ? string.Empty : project.StartDate;
                project.EndDate = string.IsNullOrEmpty(project.EndDate) ? string.Empty : project.EndDate;
                int page = 0;
                if (!int.TryParse(HttpContext.Request.Params["page"], out page))
                {
                    page = 1;
                }
                page = page == 0 ? 1 : page;
                int rows = 0;
                if (!int.TryParse(HttpContext.Request.Params["rows"], out rows))
                {
                    rows = 50;
                }
                rows = rows == 0 ? 50 : rows;
                DataSet dst = ServiceModel.CreateInstance().Client.GetProject(Session[CookieModel.UserName.ToString()].ToString(),project.ProjectStatus, project.CustomerName, project.CustomerTel, project.ProjectAddress, project.ProjectType, project.MachineType, project.StartDate, project.EndDate, page, rows);
                if (dst == null) return null;
                if (dst.Tables.Count != 2) return null;
                var data = from row in dst.Tables[0].AsEnumerable()
                           select new ProjectQueryModel()
                           {
                               createtime = row["createtime"].ToString().Trim(),
                               pname = row["pname"].ToString().Trim(),
                               paddress = row["paddress"].ToString().Trim(),
                               price = row["price"].ToString().Trim(),
                               customer = row["customer"].ToString().Trim(),
                               pstatus = row["pstatus"].ToString().Trim(),
                               view = row["view"].ToString().Trim()
                           };
                json.Data = new { total = Convert.ToInt32(dst.Tables[1].Rows[0][0]), rows = data };
            }
            catch { }
            return json;
        }

        [HttpPost]
        [ActionAuthentication]
        public JsonResult ModifyProjectStatus(ProjectModel project)
        {
            if (Session[CookieModel.UserName.ToString()] == null || string.IsNullOrEmpty(Session[CookieModel.UserName.ToString()].ToString()))
            {
                Redirect("Login/Index");
                return null;
            }
            JsonResult json = new JsonResult() { ContentType = "text/html" };
            int result = 0;
            string message = string.Empty;
            try
            {
                project.ProjectStatus = string.IsNullOrEmpty(project.ProjectStatus) ? string.Empty : project.ProjectStatus;
                project.ProjectStatus = project.ProjectStatus == "1" ? "登录成功" : "登录失败";
                result = ServiceModel.CreateInstance().Client.ModifyProjectStatus(Session[CookieModel.UserName.ToString()].ToString(), project.ProjectID, project.ProjectStatus);
                switch (result)
                {
                    case -1:
                        message = "没有权限";
                        break;
                    case 0:
                        message = "修改失败";
                        break;
                    case 1:
                        message = "修改成功";
                        break;
                }
            }
            catch (Exception ex)
            {
                result = 0;
                message = ex.Message;
            }
            json.Data = new { Result = result, Message = message };
            return json;
        }
    }
}

Logistics/Controllers/UserController.cs
using Logistics.Filters;
using Logistics.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace Logistics.Controllers
{
    public class UserController : Controller
    {
        //
        // GET: /User/
        [ActionAuthentication]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ActionAuthentication]
        public JsonResult Query(UserModel user)
        {
            if (Session[CookieModel.UserName.ToString()] == null || string.IsNullOrEmpty(Session[CookieModel.UserName.ToString()].ToString()))
            {
                Redirect("Login/Index");
                return null;
            }
            JsonResult json = new JsonResult() { ContentType = "text/html" };
            try
            {
                user.UserName = string.IsNullOrEmpty(user.UserName) ? string.Empty : user.UserName;
                DataSet dst = ServiceModel.CreateInstance().Client.GetAllUser(Session[CookieModel.UserName.ToString()].ToString(), user.UserName);
                if (dst == null) return null;
                if (dst.Tables.Count != 1) return null;
                if (Convert.ToInt32(dst.Tables[0].Rows[0][0]) == -1) return null;
                var data = from row in dst.Tables[0].AsEnumerable()
                           select new UserQueryModel()
                           {
                               id = Convert.ToInt32(row["id"]),
                               uname = row["uname"].ToString().Trim(),
                               rname = row["rname"].ToString().Trim(),
                               phone = row["phone"].ToString().Trim(),
                               isadmin = Convert.ToBoolean( row["isadmin"])?"是":"否"
                           };
                json.Data = new { total = Convert.ToInt32(dst.Tables[0].Rows[0][0]), rows = data };
            }
            catch { }
            return json;
        }

        private string ValidateInput(UserModel user)
        {
            string message = string.Empty;
            if (user.UserName.Length < 2 || user.UserName.Length > 10)
            {
                message = "用户名为2-10位字符";
                return message;
            }
            if (user.RealName.Length < 2 || user.RealName.Length > 10)
            {
                message = "真实姓名为2-10位字符";
                return message;
            }
            if (user.Phone.Length < 11 || user.Phone.Length > 20)
            {
                message = "联系电话为11-20位字符";
                return message;
            }
            if (!Regex.IsMatch(user.Phone, "[\\d-]+"))
            {
                message = "联系电话的格式不正确！";
                return message;
            }
            return message;
        }

        [HttpPost]
        [ActionAuthentication]
        public JsonResult Add(UserModel user)
        {
            if (Session[CookieModel.UserName.ToString()] == null || string.IsNullOrEmpty(Session[CookieModel.UserName.ToString()].ToString()))
            {
                Redirect("Login/Index");
                return null;
            }
            JsonResult json = new JsonResult() { ContentType = "text/html" };
            int result = 0;
            string message = ValidateInput(user);
            if (!string.IsNullOrEmpty(message))
            {
                json.Data = new { Result = result, Message = message };
                return json;
            }
            try
            {
                user.Password = string.IsNullOrEmpty(user.Password) ? "123456" : user.Password;
                user.Password = Md5Encrypt.CreateInstance().Encrypt(user.Password);
                result = ServiceModel.CreateInstance().Client.AddUser(Session[CookieModel.UserName.ToString()].ToString(), user.UserName, user.RealName, user.Phone, user.IsAdmin);
                switch (result)
                {
                    case -1:
                        message = "没有权限";
                        break;
                    case 0:
                        message = "添加失败";
                        break;
                    case 1:
                        message = "添加成功";
                        break;
                }
            }
            catch (Exception ex)
            {
                result = 0;
                message = ex.Message;
            }
            json.Data = new { Result = result, Message = message };
            return json;
        }

        [HttpPost]
        [ActionAuthentication]
        public JsonResult Modify(UserModel user)
        {
            if (Session[CookieModel.UserName.ToString()] == null || string.IsNullOrEmpty(Session[CookieModel.UserName.ToString()].ToString()))
            {
                Redirect("Login/Index");
                return null;
            }
            JsonResult json = new JsonResult() { ContentType = "text/html" };
            int result = 0;
            string message = ValidateInput(user);
            if (!string.IsNullOrEmpty(message))
            {
                json.Data = new { Result = result, Message = message };
                return json;
            }
            try
            {
                result = ServiceModel.CreateInstance().Client.ModifyUser(Session[CookieModel.UserName.ToString()].ToString(), user.UserID, user.UserName, user.RealName, user.Phone, user.IsAdmin);
                switch (result)
                {
                    case -1:
                        message = "没有权限";
                        break;
                    case 0:
                        message = "修改失败";
                        break;
                    case 1:
                        message = "修改成功";
                        break;
                }
            }
            catch (Exception ex)
            {
                result = 0;
                message = ex.Message;
            }
            json.Data = new { Result = result, Message = message };
            return json;
        }

        [HttpPost]
        [ActionAuthentication]
        public JsonResult Delete(UserModel user)
        {
            if (Session[CookieModel.UserName.ToString()] == null || string.IsNullOrEmpty(Session[CookieModel.UserName.ToString()].ToString()))
            {
                Redirect("Login/Index");
                return null;
            }
            JsonResult json = new JsonResult() { ContentType = "text/html" };
            int result = 0;
            string message = string.Empty;
            try
            {
                result = ServiceModel.CreateInstance().Client.DeleteUser(Session[CookieModel.UserName.ToString()].ToString(), user.UserID);
                switch (result)
                {
                    case -1:
                        message = "没有权限";
                        break;
                    case 0:
                        message = "删除失败";
                        break;
                    case 1:
                        message = "删除成功";
                        break;
                }
            }
            catch (Exception ex)
            {
                result = 0;
                message = ex.Message;
            }
            json.Data = new { Result = result, Message = message };
            return json;
        }

        [HttpPost]
        [ActionAuthentication]
        public JsonResult Current(UserModel user)
        {
            if (Session[CookieModel.UserName.ToString()] == null || string.IsNullOrEmpty(Session[CookieModel.UserName.ToString()].ToString()))
            {
                Redirect("Login/Index");
                return null;
            }
            JsonResult json = new JsonResult() { ContentType = "text/html" };
            if (Session[CookieModel.CurrentUser.ToString()]==null ||
                Session[CookieModel.CurrentAdmin.ToString()] == null ||
                string.IsNullOrEmpty(Session[CookieModel.CurrentUser.ToString()].ToString()) ||
                string.IsNullOrEmpty(Session[CookieModel.CurrentAdmin.ToString()].ToString()))
            {
                try
                {
                    DataSet dst = ServiceModel.CreateInstance().Client.GetCurrentUser(Session[CookieModel.UserName.ToString()].ToString());
                    if (dst == null) return null;
                    if (dst.Tables.Count != 2) return null;
                    StringBuilder sb = new StringBuilder();
                    foreach (DataRow drow in dst.Tables[1].Rows)
                    {
                        sb.Append(drow[0].ToString());
                        sb.Append("  ");
                    }
                    Session[CookieModel.CurrentUser.ToString()] = string.Format("登录用户:{0}&nbsp;&nbsp;&nbsp;", dst.Tables[0].Rows[0][0].ToString());
                    Session[CookieModel.CurrentAdmin.ToString()] = string.Format("系统管理员:{0}", sb.ToString().Trim());
                }
                catch { }
            }
            json.Data = new { current = Session[CookieModel.CurrentUser.ToString()].ToString(), admin = Session[CookieModel.CurrentAdmin.ToString()].ToString() };
            return json;
        }

    }
}

Logistics/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh">
<head>
    <title>@ViewBag.Title</title>
    <link href="~/Content/jquery-easyui-1.4.4/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/jquery-easyui-1.4.4/themes/icon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Content/jquery-easyui-1.4.4/jquery.easyui.min.js"></script>
    @Scripts.Render("~/bundles/jquerytics")
    <style type="text/css">
        .footer {
            width: 100%;
            text-align: center;
            line-height: 35px;
        }

        .top-bg {
            background-color: #d8e4fe;
            height: 80px;
        }

        .text-style {
            text-decoration: none;
            color: black;
            text-align: center;
        }

        .link-style {
            color: black;
        }

        table {
            border-collapse: collapse;
            border-spacing: 0;
            border-left: 1px solid #95b8e7;
            border-top: 1px solid #95b8e7;
        }

        th {
            border-right: 1px solid #95b8e7;
            border-bottom: 1px solid #95b8e7;
            padding: 5px 15px;
            height: 25px;
        }

        td {
            border-right: 1px solid #95b8e7;
            border-bottom: 1px solid #95b8e7;
            padding: 5px 15px;
        }
    </style>
    <script type="text/javascript">
        $(function () {
            getcurrentuser();
        });
    </script>
</head>

<body style="width: 80%; margin: 0px auto;">
    <div class="easyui-layout" data-options="fit:true">
        <div region="north" border="true" split="true" style="overflow: hidden; height: 40px;">
            <div style="display: inline; float: right; margin-right: 10px; margin-top: 8px; font-size: 16px;">
                <label id="current"></label>
                @Html.ActionLink("安全退出", "Loginout", "Login", null, new { @class = "link-style" })
            </div>
            <div style="float: left;font-size:16px;font-weight:bold;margin-left:20px;margin-top:8px;">
                物流系统管理平台V1.0
            </div>
        </div>
        <div region="south" border="true" split="true" style="overflow: hidden; height: 40px;">
            <div class="footer">
                <label id="admin"></label>
            </div>
        </div>
        <div region="west" split="true" title="菜单栏" style="width: 200px;">
            <div id="accpanel" class="easyui-accordion" style="position: absolute; top: 27px; left: 0px; right: 0px; bottom: 0px;">
                <div id="propanel" title="经销商项目管理" iconcls="icon-management" style="overflow: auto; padding: 10px;">
                    <ul class="easyui-tree">
                        <li iconcls="icon-sign-in">
                            @Html.ActionLink("工程项目登录", "Index", "ProEngineering", null, new { @class = "text-style", @onclick = "getcurrentpanel(0)" })
                        </li>
                        <li iconcls="icon-sign-in">
                            @Html.ActionLink("家装项目登录", "Index", "ProHourse", null, new { @class = "text-style", @onclick = "getcurrentpanel(0)" })
                        </li>
                        <li iconcls="icon-query">
                            @Html.ActionLink("登录项目查询", "Index", "Query", null, new { @class = "text-style", @onclick = "getcurrentpanel(0)" })
                        </li>
                    </ul>
                </div>
                <div id="syspanel" title="系统设置" iconcls="icon-settings" style="padding: 10px;">
                    <ul class="easyui-tree">
                        <li iconcls="icon-man-1">
                            @Html.ActionLink("用户管理", "Index", "User", null, new { @class = "text-style", @onclick = "getcurrentpanel(1)" })
                        </li>
                        <li iconcls="icon-change-password">
                            @Html.ActionLink("修改密码", "Index", "Changepwd", null, new { @class = "text-style", @onclick = "getcurrentpanel(1)" })
                        </li>
                        <li iconcls="icon-sign-out">
                            @Html.ActionLink("退出系统", "Loginout", "Login", null, new { @class = "text-style", @onclick = "getcurrentpanel(1)" })
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div id="mainPanle" region="center" style="overflow-y: auto;">
            @RenderBody()
        </div>
    </div>
</body>
</html>